tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "fd"
brew "luajit", args: ["HEAD"]
brew "tree-sitter", args: ["HEAD"]
brew "neovim", args: ["HEAD"]
brew "ripgrep"
brew "zsh-syntax-highlighting"
cask "kitty"
