require('falcon.treesitter')
require('falcon.autopairs')
require('falcon.lsp')
require('falcon.telescope')
require('falcon.colors')
require('falcon.lualine')
require('falcon.nvimtree')
require('falcon.maps')
